### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by WednesdayAd** [MISP/MISP-Taxii-Server#67]
I can read. I have all needed parameters. And thaths why I ask.
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=en_US.UTF-8
SUDO_GID=1004
OLDPWD=/home/admin
USERNAME=root
SUDO_COMMAND=/bin/su
USER=root
PWD=/home/admin/MISP-Taxii-Server
HOME=/root
SUDO_USER=admin
SUDO_UID=1000
MAIL=/var/mail/root
OPENTAXII_CONFIG=/home/admin/MISP-Taxii-Server/config/config.yaml
SHELL=/bin/bash
TERM=xterm
SHLVL=1
PYTHONPATH=.
LOGNAME=root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
LESSOPEN=| /usr/bin/lesspipe %s

and when I use script i have this error

/home/admin/MISP-Taxii-Server/scripts# python3 push_published_to_taxii.py
Traceback (most recent call last):
File "push_published_to_taxii.py", line 48, in 
cli.set_auth(username = config["taxii"]["auth"]["username"],
TypeError: 'NoneType' object is not subscriptable

**Comment by FloatingGhost** [comment]
You... opened *another* issue instead of staying on the first

Please do not do that

>I can read. I have all needed parameters

I can say with 100% confidence that this is not the case, as even running with `config.default.yaml`, the script works fine.

Please check your config files and environment variables. Additionally,  you seem to be using `sudo` where you absolutely do not need to.
